services:
  - type: web
    name: lazodeplata
    runtime: node
    plan: free
    buildCommand: npm ci && npm run build
    startCommand: npm run start
    envVars:
      - key: NODE_VERSION
        value: 24.4.0
      - key: LAZO_SECURE_COOKIE
        value: "true"